version: "2"
linters:
  enable:
    - bodyclose
    - dupl
    - errname
    - errorlint
    - exhaustive
    - gocritic
    - importas
    - misspell
    - prealloc
    - revive
  settings:
    revive:
      severity: warning
      rules:
        - name: atomic
        - name: unhandled-error
          arguments:
            - fmt.Printf
            - fmt.Fprintln
            - fmt.Println
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unreachable-code
        - name: redefines-builtin-id
        - name: defer
        - name: useless-break
        - name: unexported-naming
        - name: cognitive-complexity
          arguments:
            - 27
        - name: use-any
    staticcheck:
      checks:
        - all
        - "-ST1003"
  exclusions:
    generated: lax
    rules:
      - linters:
          - unused
        path: pkg/apis/data.act3-ace.io/(.*)/bottle_types.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
